istio-ecosystem/wasm-extensions

extensions/scaffold/BUILD
extensions/scaffold/README.md
extensions/scaffold/plugin.cc
extensions/scaffold/plugin.h

34K compiled
185K wee8-precompiled
Signed-off-by: Kuat Yessenov <kuat@google.com>

empty extension

---

.github/workflows/push.yaml
.github/workflows/test.yaml

Add post submit push

---

.github/workflows/format.yaml
.github/workflows/push.yaml
.github/workflows/test.yaml
go.mod
go.sum
test/basicauth/basicauth_test.go

Also duplicate wasm files with a more readable name for doc and configuration.

Update push and test flow to include release branches

---

.gitignore
README.md
extensions/zig_demo/README.md
extensions/zig_demo/build.zig
extensions/zig_demo/module.zig

Zig is so small you don't need an SDK!
Artifact size:
- safety on 137K
- optimized, safety off 67K
Signed-off-by: Kuat Yessenov <kuat@google.com>

add zig example

---

README.md
doc/write-a-wasm-extension-with-cpp.md

Clean up development guide doc a bit

---

CODEOWNERS

Fix code owner file.

---

extensions/basic_auth/README.md
extensions/basic_auth/plugin.cc
extensions/basic_auth/plugin_test.cc
test/basicauth/basicauth_test.go
test/basicauth/testdata/server_filter.yaml.tmpl

Update basic auth filter to accept base64 encoded credentials.

---

.github/workflows/push.yaml

Remove duplicated example Wasm file push.

---

README.md
doc/write-cpp-unit-test.md
doc/write-unit-test.md

Add guide about C++ unit test.

---

doc/release-process.md

Add a release process doc.

---

CODEOWNERS

Update code owner.

---

scripts/update-dep.sh

Update dep update script to use main branch instead of master.

---

WORKSPACE
bazel/wasm.bzl

Update deps to head of master.

---

.github/workflows/release.yaml

Update asset upload step name in release flow.

---

extensions/basic_auth/README.md
extensions/basic_auth/plugin.cc
extensions/basic_auth/plugin.h
test/basicauth/basicauth_test.go
test/basicauth/testdata/server_filter.yaml.tmpl

Add authenticate header into basic auth response.

---

extensions/basic_auth/README.md
extensions/basic_auth/plugin.cc
extensions/basic_auth/plugin.h
go.sum
test/basicauth/basicauth_test.go
test/basicauth/testdata/server_filter.yaml.tmpl

fixes https://github.com/istio-ecosystem/wasm-extensions/issues/50

Add host into basic auth rule.

---

extensions/basic_auth/README.md
extensions/basic_auth/plugin.cc
extensions/basic_auth/plugin.h
go.sum
test/basicauth/basicauth_test.go
test/basicauth/testdata/server_filter.yaml.tmpl

* Add host into basic auth rule.
* clean up
* repeated and wildcard host match.
* update comment
* fix
* update
* reword

Add host into basic auth rule. (#51)

---

README.md

Better top level read me.

---

LICENSE

Per @jakubrauch's request, specify owner of this repo.

Update owner of repo license to istio author

---

WORKSPACE
bazel/wasm.bzl
doc/write-cpp-unit-test.md
extensions/basic_auth/plugin_test.cc
extensions/grpc_logging/plugin.cc

Update deps for release-1.11

---

WORKSPACE
bazel/wasm.bzl
doc/write-cpp-unit-test.md
extensions/basic_auth/plugin_test.cc

Update dep for release-1.10.

---

doc/write-a-wasm-extension-with-cpp.md
doc/write-integration-test.md
example/WORKSPACE
example/test/example_test.go
extensions/basic_auth/config/gateway-filter.yaml
scripts/update-guide.sh

Update Wasm extension guide.

---

WORKSPACE
bazel/wasm.bzl
doc/write-cpp-unit-test.md
extensions/basic_auth/plugin_test.cc
extensions/grpc_logging/plugin.cc

Update deps at master.

---

doc/how-to-build-oci-images.md

Add How to build Wasm Plugin compatible OCI images.

---

.github/workflows/release.yaml

Push Wasm module oci image at release.

---

WORKSPACE
bazel/wasm.bzl

[release-1.12] update deps

---

.github/workflows/release.yaml

Remove gcloud from release flow.

---

extensions/grpc_logging/plugin.cc

fix bug;
When req_ buffer_ Req after the data in is successfully, sent_ buffer_ This data still exists in.
We should clear the data in req_ buffer_

Clean up req_buffer_ sent successfully from the req_buffer_

---

.github/workflows/test.yaml
extensions/basic_auth/README.md

Signed-off-by: hejianpeng <hejianpeng2@huawei.com>
correct link

correct link
